import fs from 'node:fs';import * as T from 'three';
import {lampFixture} from './support/lamp-scene-fixture.mjs';
const before=process.argv.includes('--before'),tag=before?'before':'after',dir=new URL('../../docs/redesign/session-10-lamp-lighting/',import.meta.url);
const api=await lampFixture(before),h=api.mount({night:true,reduced:true});h.frame();
let emitter,spot;h.scene.traverse(o=>{if(o.isMesh&&o.geometry.type==='CircleGeometry')emitter=o;if(o.isSpotLight)spot=o;});
const v=a=>new T.Vector3(...a),position=emitter.getWorldPosition(new T.Vector3()),normal=v([0,0,1]).transformDirection(emitter.matrixWorld),source=spot.getWorldPosition(new T.Vector3()),target=spot.target.getWorldPosition(new T.Vector3()),direction=target.clone().sub(source).normalize();
const head=emitter.parent,opening=head.localToWorld(v([0,-.26,0])),outward=v([0,-1,0]).transformDirection(head.matrixWorld);
const ray=new T.Raycaster(),hits=[];for(const [label,origin] of [['below',position.clone().add(outward.clone().multiplyScalar(2))],['above',position.clone().add(outward.clone().multiplyScalar(-2))]]){ray.set(origin,position.clone().sub(origin).normalize());hits.push({label,first:ray.intersectObject(h.object,true)[0]?.object===emitter?'emitter':'shell/structure/none',emitterHit:ray.intersectObject(emitter,false).length>0});}
const meshes=[];h.object.traverse(o=>{if(!o.isMesh)return;const a=o.geometry.attributes.position,n=o.geometry.attributes.normal,nm=new T.Matrix3().getNormalMatrix(o.matrixWorld),positions=[],normals=[];for(let i=0;i<a.count;i++){positions.push(new T.Vector3().fromBufferAttribute(a,i).applyMatrix4(o.matrixWorld).toArray());if(n)normals.push(new T.Vector3().fromBufferAttribute(n,i).applyNormalMatrix(nm).toArray())}const m=o.material;meshes.push({name:o===emitter?'diffuser':o.name,root:'lamp',positions,normals,indices:o.geometry.index?[...o.geometry.index.array]:Array.from({length:a.count},(_,i)=>i),color:m.color.toArray(),emissive:m.emissive.toArray(),emissiveIntensity:m.emissiveIntensity,side:m.side,castShadow:o.castShadow,receiveShadow:o.receiveShadow,roughness:m.roughness,metalness:m.metalness});});
const measurements={tag,emitter:{position:position.toArray(),normal:normal.toArray(),radius:emitter.geometry.parameters.radius,side:emitter.material.side,emission:emitter.material.emissiveIntensity},opening:opening.toArray(),outward:outward.toArray(),normalAlignment:normal.dot(outward),spot:{position:source.toArray(),target:target.toArray(),direction:direction.toArray(),axisAlignment:direction.dot(outward),intensity:spot.intensity,angle:spot.angle,penumbra:spot.penumbra,distance:spot.distance,decay:spot.decay,near:spot.shadow.camera.near,bias:spot.shadow.bias,normalBias:spot.shadow.normalBias,mapSize:spot.shadow.mapSize.toArray()},rays:hits};
fs.writeFileSync(new URL(tag+'-measurements.json',dir),JSON.stringify(measurements,null,2)+'\n');fs.writeFileSync(new URL(tag+'-lamp.json',dir),JSON.stringify({tag,meshes})+'\n');console.log(JSON.stringify(measurements,null,2));
